name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rm -rf node_modules
          npm install
          npm run lint && npm run rollup -c rollup.config.js
          ls -R ./dist
      # - name: HACS validation
      #   uses: 'hacs/action@main'
      #   with:
      #     category: 'plugin'
