name: Release

on:
  release:
    types: [published]

env:
  NODE_VERSION: 20  # Define la versión de Node.js a utilizar

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ env.NODE_VERSION }}  # Propaga la variable de entorno al trabajo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Verify environment
      - name: Verify environment
        run: |
          echo "Current directory: $(pwd)"
          ls -al
          node -v
          npm -v

      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run build
          ls -R dist

      # Upload build file to the release as an asset
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
