name: 'Release'

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build
      - name: Build the file
        run: |
          rm -rf /home/runner/work/platinum-weather-card-es/platinum-weather-card-es/node_modules
          cd /home/runner/work/platinum-weather-card-es/platinum-weather-card-es
          npm install
          npm run build
          ls -R /home/runner/work/platinum-weather-card/platinum-weather-card-es/dist

      # Upload build file to the releas as an asset.
      - name: Upload javascript to release
        uses: svenstaro/upload-release-action@v2

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/platinum-weather-card-es/platinum-weather-card-es/dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
