name: 'Release'

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the file
      - name: Build the file
        run: |
          npm run build
          ls -R dist

      # Upload build files to the release as assets
      - name: Upload all build files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/**
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          file_glob: true
